apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: test-cluster
  region: us-east-1

nodeGroups:
  - name: nodeGroup2
    instanceType: t2.micro
    desiredCapacity: 2
    ssh:
      publicKeyPath: ~/.ssh/pbaitule_aws_pub
