apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: test-cluster
  region: us-east-1

nodeGroups:
  - name: nodeGroup
    instanceType: m5.large
    desiredCapacity: 2
    minSize: 2
    maxSize: 2
    ssh:
      publicKeyPath: ~/.ssh/pbaitule_aws.pub
