apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: test-cluster
  region: us-east-1

nodeGroups:
  - name: nodeGroup
    instanceType: t2.micro
    desiredCapacity: 0
    minSize: 0
    maxSize: 2
    ssh:
      publicKeyPath: ~/.ssh/pbaitule_aws_pub
