apiVersion: helm.fluxcd.io/v1
kind: HelmRelease

metadata:
  name: nginx
  namespace: default

spec:
  chart:
    git: https://github.com/pbaitule/platform-eks.git
    name: platform-eks
    path: nginx
    ref: master
  values:
    replicaCount: 3
