apiVersion: v1
kind: Service

metadata:
  name: loadbalancerservice
  labels:
    run: loadbalancerservice

spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
