apiVersion: apps/v1
kind: Deployment

metadata:
  name: nginx-webserver
  labels:
    app: nginx

spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: pbaitule/basic-nginx-webserver:9addf590442604f4d13d9c8a8596ad674f1fd6b5
          ports:
            - containerPort: 80
